name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    permissions:
      contents: write # for asset upload
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v6

      - name: Get Color with Classes
        uses: actions/checkout@v6
        with:
          repository: vdelachaux/Color-with-Classes
          path: Components/Color-with-Classes.4dbase

      - name: Build
        uses: ./.github/actions/4d-build
        with:
          actions: "build,pack,archive"
          token: ${{ secrets.DLTK }}

      - name: Upload
        run: |
          gh release upload ${{ github.event.release.tag_name }} BUILD/${{ github.event.repository.name }}.zip
